### ISSUE TITLE
Cannot run workflows on pegasus engine

### ISSUE THREAD

**Issue by fhidalgl** [IKCAP/wings#29]
Hello,
I have a workflow running in local environment but if I change to Pegasus execution engine I receive the following error in log file:
java.lang.ClassCastException: edu.isi.wings.execution.engine.api.impl.pegasus.PegasusExecutionEngine cannot be cast to edu.isi.wings.execution.engine.api.StepExecutionEngine
	at edu.isi.wings.execution.engine.ExecutionFactory.createStepExecutionEngine(ExecutionFactory.java:36)
	at edu.isi.wings.portal.classes.config.Config.getDomainExecutionEngine(Config.java:550)
	at edu.isi.wings.portal.controllers.PlanController.setMachineWhitelist(PlanController.java:103)
	at edu.isi.wings.portal.controllers.PlanController.<init>(PlanController.java:99)
	at edu.isi.wings.portal.servlets.Planner.doGet(Planner.java:60)
	at edu.isi.wings.portal.servlets.Planner.doPost(Planner.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:41)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:268)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:612)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Can you help me?

Thank you!

**Comment by IKCAP** [comment]
Rajiv, would you be able to look at this when you get the time ?

**Comment by mayani** [comment]
@IKCAP I looked in to. I was able to compile from source, and run a Pegasus workflow end-to-end?

**Comment by mayani** [comment]
@fhidalgl Can you verify that you have the most recent version of the code checked out? The commit hash should be a7248eb1dd4fd966e4a02f3ee4dd927fc8847c7e. 

Also, can you let me know what domain are you using. Did you create one from scratch, or use one of the sample domains? If you used a sample domain, what WINGS template are you running?

The info. above will help me recreate the issue.

**Comment by fhidalgl** [comment]
Although my running version was a few weeks ago, I compiled the coded an redeployed and now it seems to work fine.
Sorry for the inconvenience.
Thank you!
